### ISSUE TITLE
The ./resources link is not available

### ISSUE THREAD

**Issue by junzhang2016** [dorian3d/DLoopDetector#12]
Since the package provides some resources to run the demo_brief, but the link provided in the CMakeLists.txt : http://doriangalvez.com/resources/DLoopDetector/resources.tar.gz, is not available, may be because the author modified his personal website.

But I found the sources from http://webdiis.unizar.es/~dorian/index.php?p=33. Now I am trying to download from this link and run the demo. If I succeed I will report here.
Thanks.

**Comment by dorian3d** [comment]
The resources are also available here: https://drive.google.com/uc?export=download&id=1MpZwPjXDAUxKfSTpeCjG0PAUpaeWuo7D
You have to download the `resources.tar.gz` file to the build directory (where you run `cmake`).

**Comment by junzhang2016** [comment]
Thanks, Dorian. I have successfully run the demo _demo_brief_ with the provided
`resources.tar.gz`
